---

- name: Run apt-get update
  become: yes
  raw: apt-get update

- name: Install python-simplejson
  become: yes
  raw: apt-get install -y python3-simplejson

- name: Reconfigure buggy ubuntu locales
  become: yes
  template: src=../files/locale dest=/etc/default/locale
    owner=root mode="u=rw,g=r,o=r" force=yes

- name: Create ubuntu user
  become: yes
  user:
    name: ubuntu
    shell: /bin/bash
    groups: sudo

- name: Upload ssh key file "{{ pub_key_file }}"
  become: yes
  authorized_key: user=ubuntu key="{{ lookup('file', '{{ pub_key_file }}') }}"
  when: upload_key

- name: Install misc packages
  become: yes
  apt:
    name: ['htop', 'iotop', 'mc', 'gcc', 'git', 'software-properties-common',
           'python3-pip', 'libssl-dev']
    state: present
    update_cache: yes

- name: Set default python version
  become: yes
  raw: >
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1 &&
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.5 2 &&
    sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip2.7 1 &&
    sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3.5 2 &&

- name: Update pip
  become: yes
  pip:
    name: pip
    state: latest

- name: Add a swap file if doesn't exist
  become: yes
  script: increase_swap.sh {{ swapsize }}
  when: swapsize|int > 0

- name: Set timezone
  become: yes
  timezone: name={{ time_zone_name | default('UTC') }}
