# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  
  #config.vm.box = "ubuntu/trusty64"
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 3010, host: 3010
  config.vm.network "forwarded_port", guest: 5001, host: 5001
  config.vm.network "forwarded_port", guest: 5123, host: 5123

  config.vm.network "forwarded_port", guest: 9200, host: 9201
  config.vm.network "forwarded_port", guest: 5601, host: 5602
  config.vm.network "forwarded_port", guest: 5672, host: 5673
  config.vm.network "forwarded_port", guest: 15672, host: 15673

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  #config.ssh.insert_key = false
  #config.ssh.username = "ubuntu"
  #config.ssh.private_key_path = ["/home/intsco/.ssh/id_rsa"]

  #config.vm.synced_folder "/opt/data", "/data"
  
  config.vm.provider "virtualbox" do |v|
    v.name = "sm-engine"
    v.memory = 8096
	v.cpus = 4
  end

  #config.vm.provision "file", source: "keys/public", destination: "~/.ssh/authorized_keys"

  config.vm.provision :ansible do |ansible|
    ansible.verbose = "vv"
    ansible.inventory_path = "hosts"
    ansible.playbook = "system.yml"
    ansible.extra_vars = {pub_key_file: "~/.ssh/id_rsa.pub"}
    ansible.host_key_checking = false
  end
end
