---

- name: Delete all local and remote branches except for 'master'
  shell: |
    git remote prune origin
    git checkout master
    git for-each-ref --format '%(refname:short)' refs/heads |
      grep -v master |
      xargs --no-run-if-empty git branch -D
  args:
    chdir: "{{ metaspace_home }}"
  when: local_deploy is not defined

- name: Pull metaspace "{{ metaspace_branch }}" branch from the repository
  git:
    repo: "{{ metaspace_repo_url }}"
    version: "{{ metaspace_branch }}"
    dest: "{{ metaspace_home }}"
    update: yes
    force: yes
  when: local_deploy is not defined
#  register: git_deploy
#  until: git_deploy | succeeded

# FIXME: double check all exclude paths
- name: Upload local files
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    rsync_opts: "{{ item.rsync_opts }}"
  when: local_deploy is defined
  with_items:
    - src: "{{ sm_ansible_home }}/"
      dest: "{{ sm_ansible_home }}/"
      rsync_opts:
        - --exclude=.*
  tags: [sm-cluster-autostart]

#    - src: "{{ sm_graphql_home }}/"
#      dest: "{{ sm_graphql_home }}/"
#      rsync_opts:
#        - --exclude='config/*.js'
#        - --exclude='logs/*'
#        - --exclude='dist/*'
#        - --exclude='node_modules/*'
#        - --exclude='.*'
#    - src: "{{ sm_webapp_home }}/"
#      dest: "{{ sm_webapp_home }}/"
#      rsync_opts:
#        - --exclude='config/*.js'
#        - --exclude=S3/*
#        - --exclude='logs/*'
#        - --exclude='dist/*'
#        - --exclude='node_modules/*'
#        - --exclude='.*'
#    - src: "{{ mol_db_home }}/"
#      dest: "{{ mol_db_home }}/"
#      rsync_opts:
#        - --exclude='conf/*'
#        - --exclude='logs'
#        - --exclude='.*'
#    - src: "{{ sm_home }}/"
#      dest: "{{ sm_home }}/"
#      rsync_opts:
#        - --exclude=.*
#        - --exclude=config/*
#        - --exclude=logs/*
#        - --exclude=docker/*
#        - --exclude=docs/*
