codecov:
  notify:
    require_ci_to_pass: yes

comment: false

coverage:
  precision: 2
  round: down

  status:
    project:
      engine:
        target: 69%
        threshold: 0.2
        flags: ["engine"]
      webapp:
        target: 51%
        threshold: 0.5
        flags: ["webapp"]
      graphql:
        target: 62%
        threshold: 0.5
        flags: ["graphql"]
    patch: no
    changes: no
