---

- name: Make sure .aws directory exists
  file: path=/home/ubuntu/.aws/
        state=directory mode=0755
        owner=ubuntu group=ubuntu
  when: aws_access_key_id is defined

- name: Put aws credentials file into the home dir
  template: src=aws_credentials.j2
            dest=/home/ubuntu/.aws/credentials mode=0600
            owner=ubuntu group=ubuntu
  when: aws_access_key_id is defined

- name: Create /opt/dev directory
  file: dest=/opt/dev state=directory owner=ubuntu group=ubuntu mode=0700
  become: yes

- name: Clone SM engine git repository
  git: >
    dest=/opt/dev/sm
    repo=https://github.com/SpatialMetabolomics/sm-engine.git
    update=yes
    force=yes
    version={{ sm_branch }}

- name: Install psycopg2 (required by ansible)
  apt: name=python-psycopg2 state=latest
  become: yes

- name: Create sm postgres user
  postgresql_user: name=sm password={{ sm_postgres_password }} role_attr_flags=CREATEDB
  become: yes
  become_user: postgres

- name: Create sm postgres database
  become: yes
  become_user: postgres
  postgresql_db: name=sm owner=sm encoding=UTF8 template=template0

- name: Create sm schema
  shell: psql -h localhost -U sm sm < /opt/dev/sm/scripts/create_schema.sql
  args:
    executable: /bin/bash
  when: sm_create_schema

- name: Create /opt/data/sm_data directory
  file: dest=/opt/data/sm_data state=directory owner=ubuntu group=ubuntu mode=0700
  become: yes

- name: Pull SM config from the remote host
  fetch: src={{ sm_home }}/conf/config.json.template dest=/tmp/config.json.template
         flat=yes fail_on_missing=yes

- name: Put SM config to {{ sm_home }}/conf/config.json
  template: src=/tmp/config.json.template dest={{ sm_home }}/conf/config.json
            owner=ubuntu group=ubuntu mode=0600

- name: Uninstall SM from conda environment
  args:
    chdir: "{{ sm_home }}"
    executable: /bin/bash
  shell: "{{ sm_activate_venv }} && pip uninstall -y sm"
  ignore_errors: yes

- name: Install SM into conda environment
  args:
    chdir: "{{ sm_home }}"
    executable: /bin/bash
  shell: "{{ sm_activate_venv }} && pip install ."

- name: Make sure that a directory for the SM logs exists
  file: path={{ sm_home }}/logs state=directory mode=0755

- name: Copy sm-api supervisor config file
  template: src=sm-api.supervisor.j2 dest=/etc/supervisor/sm-api.supervisor
            mode=0600 owner=ubuntu group=ubuntu

- name: Create SM ElasticSearch index
  shell: "{{ sm_activate_venv }} && python scripts/create_es_index.py --drop"
  args:
    chdir: "{{ sm_home }}"
    executable: /bin/bash
  when: sm_create_es_index
