version: '2'

services:

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:5.5
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - sm
    depends_on:
      - elasticsearch

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # to use rabbitmq from host
      - "15672:15672" #management interface

  postgres:
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "9000:8080"
    networks:
      - sm

  sm-api:
    volumes:
      - "${DEV_ROOT}/:/opt/dev/metaspace:z"
      - ./sm-engine/rebuild-es-index.sh:/rebuild-es-index.sh:ro
      - ./sm-engine/start-api.sh:/start-api.sh:ro
      - ./sm-engine/start-common.sh:/start-common.sh:ro
      - ./sm-engine/install-dbs.sh:/install-dbs.sh:ro
    environment:
      - SM_DOCKER_ENV=development
    ports:
      - "5123:5123"

  sm-update-daemon:
    volumes:
      - "${DEV_ROOT}/:/opt/dev/metaspace:z"
      - ./sm-engine/start-update-daemon.sh:/start-update-daemon.sh:ro
      - ./sm-engine/start-common.sh:/start-common.sh:ro
    environment:
      - SM_DOCKER_ENV=development

  sm-annotate-daemon:
    volumes:
      - "${DEV_ROOT}/:/opt/dev/metaspace:z"
      - ./sm-engine/start-annotate-daemon.sh:/start-annotate-daemon.sh:ro
      - ./sm-engine/start-common.sh:/start-common.sh:ro
    environment:
      - SM_DOCKER_ENV=development

  sm-graphql:
    volumes:
      - "${DEV_ROOT}/:/opt/dev/metaspace:z"
      - ./sm-graphql/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    environment:
      - SM_DOCKER_ENV=development
    ports:
      - "3010:3010"
      - "5666:5666"
      - "4201:4201"

  sm-webapp:
    volumes:
      - "${DEV_ROOT}/:/opt/dev/metaspace:z"
      - ./sm-webapp/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    environment:
      - SM_DOCKER_ENV=development
    ports:
      - "8082:8082"

  nginx:
    ports:
      - "9210:9210" # password-protected kibana proxy
    # Use extra_hosts to map DNS names to the host if you need to run any of the applications outside of docker
    # extra_hosts:
    #   - "sm-webapp:172.17.0.1"
    #   - "sm-graphql:172.17.0.1"
