version: '2'

services:

  postgres:
    # The default mount point for pgdata isn't accessible to other users, so move it
    volumes:
      - ./data/pgdata:/pgdata
    environment:
      PGDATA: /pgdata
    user: "$SM_USER"

  sm-api:
    user: "$SM_USER"

  sm-update-daemon:
    user: "$SM_USER"

  sm-annotate-daemon:
    user: "$SM_USER"

  sm-graphql:
    user: "$SM_USER"

  sm-webapp:
    user: "$SM_USER"