---

- name: Spinning up AWS instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    components: ''

  tasks:
    - debug: var=components
    - debug: var=aws_key_name

    - name: Spin up SM instances
      shell: >
        {{ sm_cluster_autostart_python }} aws_instance_manager.py create --key-name {{ aws_key_name }}
        --components {{ components }} --stage {{ stage }}
        {{ ' --credentials-file' if cred_file is defined else '' }}

    - meta: refresh_inventory

  tags: ["web", "spark", "elk"]


- name: Wait for SSH on Spark instances to come up
  hosts: master, slave
  user: ubuntu
  gather_facts: no

  tasks:
    - name: Wait for instance to become reachable over SSH
      wait_for_connection:
        timeout: 300

    - name: Gather facts for first time
      setup:

  tags: ["spark"]
