---

- name: Stop daemons on master
  hosts: master
  user: ubuntu

  tasks:
    - name: Stop all daemons managed by supervisor on master
      shell: supervisorctl stop all
      register: res
      failed_when: false

    - debug: var=res.stdout


- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    components: ''

  tasks:
    - name: Stopping SM cluster instances
      shell: "{{ sm_cluster_autostart_python }} aws_instance_manager.py stop --key-name {{ aws_key_name }}
             --components {{ components }} --stage {{ stage }}
             {{ ' --credentials-file' if cred_file is defined else '' }}"
