---

- name: Stop daemons on master
  hosts: master
  user: ubuntu

  tasks:
    - name: Stop all daemons managed by supervisor on master
      command: supervisorctl stop all
      register: res

    - debug: var=res.stdout


- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    components: ''

  tasks:
    - name: Stopping SM cluster instances
      shell: python3 aws_instance_manager.py stop --key-name {{ aws_key_name }}
             --components {{ components }} --stage {{ stage }}
