---

- name: Spinning up AWS instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    components: ''

  tasks:
    - debug: var=components
    - debug: var=aws_key_name

    - name: Spin up SM instances
      shell: >
        {{ sm_aws_python }} aws_instance_manager.py create --key-name {{ aws_key_name }}
        --components {{ components }} --stage {{ stage }}
        {{ ' --credentials-file' if cred_file is defined else '' }}

    - meta: refresh_inventory

  tags: ["web", "elk"]
