---

- name: Stop SM cluster instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    components: ''

  tasks:
    - shell: >
        {{ sm_aws_python }} aws_instance_manager.py stop
        --key-name {{ aws_key_name }}
        --components {{ components }} --stage {{ stage }}
        {{ ' --credentials-file' if cred_file is defined else '' }}
