// Stripe Tax supported countries - based on Stripe documentation
// https://docs.stripe.com/tax/supported-countries

export interface Country {
  code: string
  name: string
  requiresPostalCode: boolean
}

export const STRIPE_SUPPORTED_COUNTRIES: Country[] = [
  // Major markets - USA, UK, EU, China
  { code: 'US', name: 'United States', requiresPostalCode: true },
  { code: 'GB', name: 'United Kingdom', requiresPostalCode: true },
  { code: 'CN', name: 'China', requiresPostalCode: true },

  // EU Countries
  { code: 'AT', name: 'Austria', requiresPostalCode: true },
  { code: 'BE', name: 'Belgium', requiresPostalCode: true },
  { code: 'BG', name: 'Bulgaria', requiresPostalCode: true },
  { code: 'HR', name: 'Croatia', requiresPostalCode: true },
  { code: 'CY', name: 'Cyprus', requiresPostalCode: true },
  { code: 'CZ', name: 'Czech Republic', requiresPostalCode: true },
  { code: 'DK', name: 'Denmark', requiresPostalCode: true },
  { code: 'EE', name: 'Estonia', requiresPostalCode: true },
  { code: 'FI', name: 'Finland', requiresPostalCode: true },
  { code: 'FR', name: 'France', requiresPostalCode: true },
  { code: 'DE', name: 'Germany', requiresPostalCode: true },
  { code: 'GR', name: 'Greece', requiresPostalCode: true },
  { code: 'HU', name: 'Hungary', requiresPostalCode: true },
  { code: 'IE', name: 'Ireland', requiresPostalCode: true },
  { code: 'IT', name: 'Italy', requiresPostalCode: true },
  { code: 'LV', name: 'Latvia', requiresPostalCode: true },
  { code: 'LT', name: 'Lithuania', requiresPostalCode: true },
  { code: 'LU', name: 'Luxembourg', requiresPostalCode: true },
  { code: 'MT', name: 'Malta', requiresPostalCode: true },
  { code: 'NL', name: 'Netherlands', requiresPostalCode: true },
  { code: 'PL', name: 'Poland', requiresPostalCode: true },
  { code: 'PT', name: 'Portugal', requiresPostalCode: true },
  { code: 'RO', name: 'Romania', requiresPostalCode: true },
  { code: 'SK', name: 'Slovakia', requiresPostalCode: true },
  { code: 'SI', name: 'Slovenia', requiresPostalCode: true },
  { code: 'ES', name: 'Spain', requiresPostalCode: true },
  { code: 'SE', name: 'Sweden', requiresPostalCode: true },

  // Additional European countries (non-EU)
  { code: 'CH', name: 'Switzerland', requiresPostalCode: true },
  { code: 'NO', name: 'Norway', requiresPostalCode: true },
  { code: 'IS', name: 'Iceland', requiresPostalCode: true },

  // Commented out - all other countries for future use
  /*
  { code: 'AD', name: 'Andorra', requiresPostalCode: true },
  { code: 'AE', name: 'United Arab Emirates', requiresPostalCode: false },
  { code: 'AG', name: 'Antigua and Barbuda', requiresPostalCode: false },
  { code: 'AI', name: 'Anguilla', requiresPostalCode: true },
  { code: 'AL', name: 'Albania', requiresPostalCode: true },
  { code: 'AM', name: 'Armenia', requiresPostalCode: true },
  { code: 'AO', name: 'Angola', requiresPostalCode: false },
  { code: 'AR', name: 'Argentina', requiresPostalCode: true },
  { code: 'AS', name: 'American Samoa', requiresPostalCode: true },
  { code: 'AU', name: 'Australia', requiresPostalCode: true },
  { code: 'AW', name: 'Aruba', requiresPostalCode: false },
  { code: 'AX', name: 'Åland Islands', requiresPostalCode: true },
  { code: 'AZ', name: 'Azerbaijan', requiresPostalCode: true },
  { code: 'BA', name: 'Bosnia and Herzegovina', requiresPostalCode: true },
  { code: 'BB', name: 'Barbados', requiresPostalCode: true },
  { code: 'BD', name: 'Bangladesh', requiresPostalCode: true },
  { code: 'BF', name: 'Burkina Faso', requiresPostalCode: false },
  { code: 'BH', name: 'Bahrain', requiresPostalCode: true },
  { code: 'BI', name: 'Burundi', requiresPostalCode: false },
  { code: 'BJ', name: 'Benin', requiresPostalCode: false },
  { code: 'BL', name: 'Saint Barthélemy', requiresPostalCode: true },
  { code: 'BM', name: 'Bermuda', requiresPostalCode: true },
  { code: 'BN', name: 'Brunei', requiresPostalCode: true },
  { code: 'BO', name: 'Bolivia', requiresPostalCode: true },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', requiresPostalCode: false },
  { code: 'BR', name: 'Brazil', requiresPostalCode: true },
  { code: 'BS', name: 'Bahamas', requiresPostalCode: false },
  { code: 'BT', name: 'Bhutan', requiresPostalCode: true },
  { code: 'BV', name: 'Bouvet Island', requiresPostalCode: false },
  { code: 'BW', name: 'Botswana', requiresPostalCode: false },
  { code: 'BY', name: 'Belarus', requiresPostalCode: true },
  { code: 'BZ', name: 'Belize', requiresPostalCode: false },
  { code: 'CA', name: 'Canada', requiresPostalCode: true },
  { code: 'CC', name: 'Cocos (Keeling) Islands', requiresPostalCode: true },
  { code: 'CD', name: 'Congo, Democratic Republic of the', requiresPostalCode: false },
  { code: 'CF', name: 'Central African Republic', requiresPostalCode: false },
  { code: 'CG', name: 'Congo', requiresPostalCode: false },
  { code: 'CI', name: 'Côte d\'Ivoire', requiresPostalCode: false },
  { code: 'CK', name: 'Cook Islands', requiresPostalCode: false },
  { code: 'CL', name: 'Chile', requiresPostalCode: true },
  { code: 'CM', name: 'Cameroon', requiresPostalCode: false },
  { code: 'CO', name: 'Colombia', requiresPostalCode: true },
  { code: 'CR', name: 'Costa Rica', requiresPostalCode: true },
  { code: 'CU', name: 'Cuba', requiresPostalCode: true },
  { code: 'CV', name: 'Cape Verde', requiresPostalCode: true },
  { code: 'CW', name: 'Curaçao', requiresPostalCode: false },
  { code: 'CX', name: 'Christmas Island', requiresPostalCode: true },
  { code: 'DJ', name: 'Djibouti', requiresPostalCode: false },
  { code: 'DM', name: 'Dominica', requiresPostalCode: false },
  { code: 'DO', name: 'Dominican Republic', requiresPostalCode: true },
  { code: 'DZ', name: 'Algeria', requiresPostalCode: true },
  { code: 'EC', name: 'Ecuador', requiresPostalCode: true },
  { code: 'EG', name: 'Egypt', requiresPostalCode: true },
  { code: 'EH', name: 'Western Sahara', requiresPostalCode: false },
  { code: 'ER', name: 'Eritrea', requiresPostalCode: false },
  { code: 'ET', name: 'Ethiopia', requiresPostalCode: true },
  { code: 'FJ', name: 'Fiji', requiresPostalCode: false },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', requiresPostalCode: true },
  { code: 'FM', name: 'Micronesia, Federated States of', requiresPostalCode: true },
  { code: 'FO', name: 'Faroe Islands', requiresPostalCode: true },
  { code: 'GA', name: 'Gabon', requiresPostalCode: false },
  { code: 'GD', name: 'Grenada', requiresPostalCode: false },
  { code: 'GE', name: 'Georgia', requiresPostalCode: true },
  { code: 'GF', name: 'French Guiana', requiresPostalCode: true },
  { code: 'GG', name: 'Guernsey', requiresPostalCode: true },
  { code: 'GH', name: 'Ghana', requiresPostalCode: false },
  { code: 'GI', name: 'Gibraltar', requiresPostalCode: true },
  { code: 'GL', name: 'Greenland', requiresPostalCode: true },
  { code: 'GM', name: 'Gambia', requiresPostalCode: false },
  { code: 'GN', name: 'Guinea', requiresPostalCode: false },
  { code: 'GP', name: 'Guadeloupe', requiresPostalCode: true },
  { code: 'GQ', name: 'Equatorial Guinea', requiresPostalCode: false },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', requiresPostalCode: true },
  { code: 'GT', name: 'Guatemala', requiresPostalCode: true },
  { code: 'GU', name: 'Guam', requiresPostalCode: true },
  { code: 'GW', name: 'Guinea-Bissau', requiresPostalCode: true },
  { code: 'GY', name: 'Guyana', requiresPostalCode: false },
  { code: 'HK', name: 'Hong Kong', requiresPostalCode: false },
  { code: 'HM', name: 'Heard Island and McDonald Islands', requiresPostalCode: true },
  { code: 'HN', name: 'Honduras', requiresPostalCode: true },
  { code: 'HT', name: 'Haiti', requiresPostalCode: true },
  { code: 'ID', name: 'Indonesia', requiresPostalCode: true },
  { code: 'IL', name: 'Israel', requiresPostalCode: true },
  { code: 'IM', name: 'Isle of Man', requiresPostalCode: true },
  { code: 'IN', name: 'India', requiresPostalCode: true },
  { code: 'IO', name: 'British Indian Ocean Territory', requiresPostalCode: true },
  { code: 'IQ', name: 'Iraq', requiresPostalCode: true },
  { code: 'IR', name: 'Iran, Islamic Republic of', requiresPostalCode: true },
  { code: 'JE', name: 'Jersey', requiresPostalCode: true },
  { code: 'JM', name: 'Jamaica', requiresPostalCode: true },
  { code: 'JO', name: 'Jordan', requiresPostalCode: true },
  { code: 'JP', name: 'Japan', requiresPostalCode: true },
  { code: 'KE', name: 'Kenya', requiresPostalCode: true },
  { code: 'KG', name: 'Kyrgyzstan', requiresPostalCode: true },
  { code: 'KH', name: 'Cambodia', requiresPostalCode: true },
  { code: 'KI', name: 'Kiribati', requiresPostalCode: false },
  { code: 'KM', name: 'Comoros', requiresPostalCode: false },
  { code: 'KN', name: 'Saint Kitts and Nevis', requiresPostalCode: false },
  { code: 'KP', name: 'Korea, Democratic People\'s Republic of', requiresPostalCode: false },
  { code: 'KR', name: 'Korea, Republic of', requiresPostalCode: true },
  { code: 'KW', name: 'Kuwait', requiresPostalCode: true },
  { code: 'KY', name: 'Cayman Islands', requiresPostalCode: true },
  { code: 'KZ', name: 'Kazakhstan', requiresPostalCode: true },
  { code: 'LA', name: 'Lao People\'s Democratic Republic', requiresPostalCode: true },
  { code: 'LB', name: 'Lebanon', requiresPostalCode: true },
  { code: 'LC', name: 'Saint Lucia', requiresPostalCode: true },
  { code: 'LI', name: 'Liechtenstein', requiresPostalCode: true },
  { code: 'LK', name: 'Sri Lanka', requiresPostalCode: true },
  { code: 'LR', name: 'Liberia', requiresPostalCode: true },
  { code: 'LS', name: 'Lesotho', requiresPostalCode: true },
  { code: 'LY', name: 'Libya', requiresPostalCode: false },
  { code: 'MA', name: 'Morocco', requiresPostalCode: true },
  { code: 'MC', name: 'Monaco', requiresPostalCode: true },
  { code: 'MD', name: 'Moldova, Republic of', requiresPostalCode: true },
  { code: 'ME', name: 'Montenegro', requiresPostalCode: true },
  { code: 'MF', name: 'Saint Martin (French part)', requiresPostalCode: true },
  { code: 'MG', name: 'Madagascar', requiresPostalCode: true },
  { code: 'MH', name: 'Marshall Islands', requiresPostalCode: true },
  { code: 'MK', name: 'North Macedonia', requiresPostalCode: true },
  { code: 'ML', name: 'Mali', requiresPostalCode: false },
  { code: 'MM', name: 'Myanmar', requiresPostalCode: true },
  { code: 'MN', name: 'Mongolia', requiresPostalCode: true },
  { code: 'MO', name: 'Macao', requiresPostalCode: false },
  { code: 'MP', name: 'Northern Mariana Islands', requiresPostalCode: true },
  { code: 'MQ', name: 'Martinique', requiresPostalCode: true },
  { code: 'MR', name: 'Mauritania', requiresPostalCode: false },
  { code: 'MS', name: 'Montserrat', requiresPostalCode: true },
  { code: 'MU', name: 'Mauritius', requiresPostalCode: true },
  { code: 'MV', name: 'Maldives', requiresPostalCode: true },
  { code: 'MW', name: 'Malawi', requiresPostalCode: false },
  { code: 'MX', name: 'Mexico', requiresPostalCode: true },
  { code: 'MY', name: 'Malaysia', requiresPostalCode: true },
  { code: 'MZ', name: 'Mozambique', requiresPostalCode: true },
  { code: 'NA', name: 'Namibia', requiresPostalCode: true },
  { code: 'NC', name: 'New Caledonia', requiresPostalCode: true },
  { code: 'NE', name: 'Niger', requiresPostalCode: true },
  { code: 'NF', name: 'Norfolk Island', requiresPostalCode: true },
  { code: 'NG', name: 'Nigeria', requiresPostalCode: true },
  { code: 'NI', name: 'Nicaragua', requiresPostalCode: true },
  { code: 'NP', name: 'Nepal', requiresPostalCode: true },
  { code: 'NR', name: 'Nauru', requiresPostalCode: false },
  { code: 'NU', name: 'Niue', requiresPostalCode: false },
  { code: 'NZ', name: 'New Zealand', requiresPostalCode: true },
  { code: 'OM', name: 'Oman', requiresPostalCode: true },
  { code: 'PA', name: 'Panama', requiresPostalCode: false },
  { code: 'PE', name: 'Peru', requiresPostalCode: true },
  { code: 'PF', name: 'French Polynesia', requiresPostalCode: true },
  { code: 'PG', name: 'Papua New Guinea', requiresPostalCode: true },
  { code: 'PH', name: 'Philippines', requiresPostalCode: true },
  { code: 'PK', name: 'Pakistan', requiresPostalCode: true },
  { code: 'PM', name: 'Saint Pierre and Miquelon', requiresPostalCode: true },
  { code: 'PN', name: 'Pitcairn', requiresPostalCode: true },
  { code: 'PR', name: 'Puerto Rico', requiresPostalCode: true },
  { code: 'PS', name: 'Palestine, State of', requiresPostalCode: true },
  { code: 'PW', name: 'Palau', requiresPostalCode: true },
  { code: 'PY', name: 'Paraguay', requiresPostalCode: true },
  { code: 'QA', name: 'Qatar', requiresPostalCode: false },
  { code: 'RE', name: 'Réunion', requiresPostalCode: true },
  { code: 'RS', name: 'Serbia', requiresPostalCode: true },
  { code: 'RU', name: 'Russian Federation', requiresPostalCode: true },
  { code: 'RW', name: 'Rwanda', requiresPostalCode: false },
  { code: 'SA', name: 'Saudi Arabia', requiresPostalCode: true },
  { code: 'SB', name: 'Solomon Islands', requiresPostalCode: false },
  { code: 'SC', name: 'Seychelles', requiresPostalCode: false },
  { code: 'SD', name: 'Sudan', requiresPostalCode: true },
  { code: 'SG', name: 'Singapore', requiresPostalCode: true },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', requiresPostalCode: true },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', requiresPostalCode: true },
  { code: 'SL', name: 'Sierra Leone', requiresPostalCode: false },
  { code: 'SM', name: 'San Marino', requiresPostalCode: true },
  { code: 'SN', name: 'Senegal', requiresPostalCode: true },
  { code: 'SO', name: 'Somalia', requiresPostalCode: true },
  { code: 'SR', name: 'Suriname', requiresPostalCode: false },
  { code: 'SS', name: 'South Sudan', requiresPostalCode: false },
  { code: 'ST', name: 'Sao Tome and Principe', requiresPostalCode: false },
  { code: 'SV', name: 'El Salvador', requiresPostalCode: true },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', requiresPostalCode: false },
  { code: 'SY', name: 'Syrian Arab Republic', requiresPostalCode: false },
  { code: 'SZ', name: 'Eswatini', requiresPostalCode: true },
  { code: 'TC', name: 'Turks and Caicos Islands', requiresPostalCode: true },
  { code: 'TD', name: 'Chad', requiresPostalCode: false },
  { code: 'TF', name: 'French Southern Territories', requiresPostalCode: false },
  { code: 'TG', name: 'Togo', requiresPostalCode: false },
  { code: 'TH', name: 'Thailand', requiresPostalCode: true },
  { code: 'TJ', name: 'Tajikistan', requiresPostalCode: true },
  { code: 'TK', name: 'Tokelau', requiresPostalCode: false },
  { code: 'TL', name: 'Timor-Leste', requiresPostalCode: false },
  { code: 'TM', name: 'Turkmenistan', requiresPostalCode: true },
  { code: 'TN', name: 'Tunisia', requiresPostalCode: true },
  { code: 'TO', name: 'Tonga', requiresPostalCode: false },
  { code: 'TR', name: 'Turkey', requiresPostalCode: true },
  { code: 'TT', name: 'Trinidad and Tobago', requiresPostalCode: false },
  { code: 'TV', name: 'Tuvalu', requiresPostalCode: false },
  { code: 'TW', name: 'Taiwan', requiresPostalCode: true },
  { code: 'TZ', name: 'Tanzania, United Republic of', requiresPostalCode: true },
  { code: 'UA', name: 'Ukraine', requiresPostalCode: true },
  { code: 'UG', name: 'Uganda', requiresPostalCode: false },
  { code: 'UM', name: 'United States Minor Outlying Islands', requiresPostalCode: true },
  { code: 'UY', name: 'Uruguay', requiresPostalCode: true },
  { code: 'UZ', name: 'Uzbekistan', requiresPostalCode: true },
  { code: 'VA', name: 'Holy See (Vatican City State)', requiresPostalCode: true },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', requiresPostalCode: true },
  { code: 'VE', name: 'Venezuela, Bolivarian Republic of', requiresPostalCode: true },
  { code: 'VG', name: 'Virgin Islands, British', requiresPostalCode: true },
  { code: 'VI', name: 'Virgin Islands, U.S.', requiresPostalCode: true },
  { code: 'VN', name: 'Viet Nam', requiresPostalCode: true },
  { code: 'VU', name: 'Vanuatu', requiresPostalCode: false },
  { code: 'WF', name: 'Wallis and Futuna', requiresPostalCode: true },
  { code: 'WS', name: 'Samoa', requiresPostalCode: false },
  { code: 'YE', name: 'Yemen', requiresPostalCode: false },
  { code: 'YT', name: 'Mayotte', requiresPostalCode: true },
  { code: 'ZA', name: 'South Africa', requiresPostalCode: true },
  { code: 'ZM', name: 'Zambia', requiresPostalCode: true },
  { code: 'ZW', name: 'Zimbabwe', requiresPostalCode: false },
  */
]

// Helper function to get country by code
export const getCountryByCode = (code: string): Country | undefined => {
  return STRIPE_SUPPORTED_COUNTRIES.find((country) => country.code === code)
}

// Helper function to check if a country requires postal code
export const countryRequiresPostalCode = (countryCode: string): boolean => {
  const country = getCountryByCode(countryCode)
  return country?.requiresPostalCode ?? false
}
