import { transform } from 'lodash-es'

export const TRANSLATE_ANALYZER : any = transform({
  'timstof flex': 'QTOF',
  qtof: 'QTOF',
  'q-exactive-orbitrap': 'Orbitrap',
  orbitrap: 'Orbitrap',
  '12t fticr': 'FTICR',
  'fticr scimax 7t': 'FTICR',
  '15 t fticr': 'FTICR',
  '7 t fticr': 'FTICR',
  fticr: 'FTICR',
  'tof reflector': 'TOF',
  '12 T FTICR': 'FTICR',
  '12T FTICR': 'FTICR',
  '15 T FTICR': 'FTICR',
  '7 T FTICR': 'FTICR',
  '7T FTICR': 'FTICR',
  'FT-ICR': 'FTICR',
  'FTICR 12T': 'FTICR',
  'FTICR scimaX 7T': 'FTICR',
  'Q-Exactive-Orbitrap': 'Orbitrap',
  'TOF reflector': 'TOF',
  qTOF: 'QTOF',
  timsTOF: 'QTOF',
  'timsTOF ': 'QTOF',
  'timsTOF Flex': 'QTOF',
  'timsTOF fleX MALDI2': 'QTOF',
  'E.g. FTICR, Orbitrap': 'Other',
  Synapt: 'QTOF',
  'Orbitrap Exploris 480': 'Orbitrap',
  FTICR: 'FTICR',
  'Q-Exactive-Orbitrap-HF': 'Orbitrap',
  QTOF: 'QTOF',
  'Xevo G2-XS': 'QTOF',
  'Orbitrap XL': 'Orbitrap',
  FTMS: 'Other',
  TOF: 'TOF',
  UHMR: 'Other',
  'Synapt G2-S MS': 'QTOF',
  'QExactive plus': 'Orbitrap',
  'N/A': 'Other',
  Orbitrap: 'Orbitrap',
  'Synapt XS': 'QTOF',
  None: 'Other',
  'orbitrap xl': 'Orbitrap',
  'q-exactive-orbitrap-hf': 'Orbitrap',
  'orbitrap exploris 240': 'Orbitrap',
  'orbitrap exploris 480': 'Orbitrap',
  '7t fticr': 'FTICR',
  '12 t fticr': 'FTICR',
  '21 t fticr': 'FTICR',
  'fticr 12t': 'FTICR',
  'fticr(solarix)': 'FTICR',
  'ft-icr': 'FTICR',
  tof: 'QTOF',
  'timstof flex maldi2': 'QTOF',
  'mr tof': 'QTOF',
  'tof ': 'QTOF',
  'maldi + tof': 'QTOF',
  'timstof ': 'QTOF',
  'buncher-tof': 'QTOF',
  timstof: 'QTOF',
  'timstof flex maldi-2': 'QTOF',
  'waters vion ims qtof mass spectrometer': 'QTOF',
}, (result, val, key) => {
  result[key.toLowerCase()] = val
})
export const TRANSLATE_SOURCE : any = transform({
  'UV-MALDESI': 'Other',
  DESI: 'DESI',
  LAESI: 'LAESI',
  'IR-MALDESI': 'IR-MALDESI',
  LDI: 'Other',
  'TG-MALDI-2': 'MALDI',
  'AP-IR-plasma-LDI': 'Other',
  'MALDI-2': 'MALDI',
  'SIMS (Bi3+)': 'SIMS',
  SIMS: 'SIMS',
  'AP-SMALDI5 AF': 'MALDI',
  'AP-SMALDI10': 'MALDI',
  'AP-SMALDI': 'MALDI',
  NanoDESI: 'NanoDESI',
  'MALDI 2': 'MALDI',
  Desi: 'DESI',
  'AP-MALDI': 'MALDI',
  'Nano-DESI': 'NanoDESI',
  'AP-SMALDI5': 'MALDI',
  HESI: 'Other',
  'AP-SMALDI 10': 'MALDI',
  MALDI: 'MALDI',
  AFADESI: 'Other',
  'AP-SMALDI 5': 'MALDI',
  't-MALDI-2': 'MALDI',
  'DESI-MSI': 'DESI',
  IRMALDESI: 'IR-MALDESI',
  LESA: 'Other',
  ESI: 'Other',
  'C60 (SIMS)': 'SIMS',
  None: 'Other',
}, (result, val, key) => {
  result[key.toLowerCase()] = val
})
export const TRANSLATE_MATRIX : any = transform({
  CHCA: 'CHCA',
  '9AA': '9AA',
  '4-Phenyl-alpha-cyanocinnamic acid amide': 'Other',
  DHA: 'Other',
  Ni: 'Other',
  Norharmane: 'Norharmane',
  '2-Mercaptobenzothiazole (MBT)': 'MBT',
  '5-chloro-2-Mercaptobenzothiazole (CMBT)': 'CMBT',
  '2,5-dihydroxybenzoic acid (DHB)': 'DHB',
  'trans-2-[3-(4-tert-Butylphenyl)-2-methyl-2-propenylidene] malononitrile (DCTB)': 'DCTB',
  '1,5-diaminonaphthalene (DAN)': 'DAN',
  THAP: 'Other',
  'N/A': 'N/A',
  '': 'N/A',
  '2,5-dihydroxybenzoic acid (DHB)/Fe3O4 binary mix': 'Mix',
  'n-(1-naphthyl)ethylenediamine dihydrochloride (NEDC)': 'NEDC',
  '4-Nitroaniline': 'PNA',
  '9-aminoacridine (9AA)': '9AA',
  BzPy: 'Other',
  '1,5-diaminonaphthalene (DAN), DHB': 'Mix',
  'alpha-cyano-4-hydroxycinnamic acid (CHCA)': 'CHCA',
  NEDC: 'NEDC',
  DAN: 'DAN',
  sDHB: 'sDHB',
  DHB: 'DHB',
  '1,8-Bis-(l-pyrrolidinyl)naphthalene': 'Other',
  'super DHB': 'sDHB',
  none: 'Other',
  '1,8,9-anthracenetriol (Dithranol)': 'Other',
  'Universal DHB CHCA': 'Mix',
  '2,5-dihydroxyacetophenone (DHAP)': '2,5-DHAP',
  '1,8-bis(dimethylamino)naphthalene (DMAN)': 'DMAN',
  'DHB/CHCA': 'Mix',
  'DHB, CHCA': 'Mix',
  '2,5-dihydroxyacetophenone (DHA)': '2,5-DHAP',
  norhramne: 'Norharmane',
  Pt: 'Other',
  SDHB: 'Other',
  DHP: 'Other',
  multiple: 'Mix',
  '1,5-diaminonaphthalene (DAN)+HCl': 'Mix',
  BPYN: 'Mix',
  'DHB/Fe3O4': 'Mix',
  '\xce\xb1-Cyano-4-hydroxycinnamic acid (HCCA)': 'CHCA',
  'DHB and DAN': 'Mix',
  DIOS: 'Other',
  '1,5-diaminonaphthalene (DAN) | DHB': 'Mix',
  Cu: 'Other',
  Ag: 'Other',
  Ti: 'Other',
  '2,5-dihydroxy benzoic acid (DHB)': 'DHB',
  Au: 'Other',
  PNA: 'PNA',
  None: 'Other',
  '2,4,6-Trihydroxyacetophenone (THAP)': 'Other',
  '2,5-dihydroxyacetophenone (DHAP)/Gold Sputter': '2,5-DHAP',
  DIUTHAME: 'Other',
  Ice: 'Other',
  ice: 'Other',
  norharmane: 'Norharmane',
  glycerol: 'Other',
  '2\xe2\x80\xb2,6\xe2\x80\xb2-Dihydroxyacetophenone (DHAP)': '2,6-DHAP',
  ZSA: 'Other',
  DHAP: 'Other',
}, (result, val, key) => {
  result[key.toLowerCase()] = val
})
