/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Colorbar: typeof import('./src/components/Colorbar.vue')['default']
    ContentPage: typeof import('./src/components/ContentPage.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    DatasetCheckboxList: typeof import('./src/components/DatasetCheckboxList.vue')['default']
    DatasetInfo: typeof import('./src/components/DatasetInfo.vue')['default']
    Dropzone: typeof import('./src/components/UppyUploader/Dropzone.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileStatus: typeof import('./src/components/UppyUploader/FileStatus.vue')['default']
    Form: typeof import('./src/components/Form/Form.vue')['default']
    ImageLoader: typeof import('./src/components/ImageLoader.vue')['default']
    MembersList: typeof import('./src/components/MembersList.vue')['default']
    MiniSwitch: typeof import('./src/components/MiniSwitch.vue')['default']
    NotificationIcon: typeof import('./src/components/NotificationIcon.vue')['default']
    PrimaryIcon: typeof import('./src/components/PrimaryIcon.vue')['default']
    RangeSlider: typeof import('./src/components/Slider/RangeSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleBar: typeof import('./src/components/ScaleBar.vue')['default']
    SecondaryIcon: typeof import('./src/components/SecondaryIcon.vue')['default']
    Slider: typeof import('./src/components/Slider/Slider.vue')['default']
    SliderThumb: typeof import('./src/components/Slider/SliderThumb.vue')['default']
    SliderTrack: typeof import('./src/components/Slider/SliderTrack.vue')['default']
    StatefulIcon: typeof import('./src/components/StatefulIcon.vue')['default']
    UppyUploader: typeof import('./src/components/UppyUploader/UppyUploader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
