---

- name: Copy sm-annotate-daemon supervisor config file
  template: src=sm-annotate-daemon.supervisor.j2 dest=/etc/supervisor/{{ sm_annotate_daemon_app_name }}.supervisor
            mode=0600 owner=ubuntu group=ubuntu

- name: Update and restart supervisor app
  supervisorctl:
    name: "{{ sm_annotate_daemon_app_name }}"
    state: restarted
