---

- name: Pull metaspace sources from the repository
  git:
    repo: "{{ metaspace_repo_url }}"
    version: "{{ metaspace_branch }}"
    dest: "{{ metaspace_home }}"
    update: yes
    force: yes
  run_once: true
  when: local_deploy is not defined
  register: git_deploy
  until: git_deploy | succeeded