FROM node:20.14.0-alpine3.20

RUN apk add --no-cache git netcat-openbsd
RUN yarn global add nodemon

WORKDIR /opt/dev/metaspace/metaspace/graphql

ENTRYPOINT [ ]
CMD [ "/sm-graphql/docker-entrypoint.sh" ]
