name: Build msi_recal wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: horvatovichlab/MSIWarp
        path: metaspace/recal/MSIWarp
        submodules: true

    - uses: actions/setup-python@v2

    - name: Build wheels
      uses: joerick/cibuildwheel@v1.10.0
      env:
        CIBW_BUILD: "*_amd64 *_x86_64"
        CIBW_SKIP: "cp27* cp35* pp*"
      with:
        package-dir: metaspace/recal

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

      #    - name: Upload wheels
      #      uses: actions/upload-artifact@v2
      #      with:
      #        path: wheelhouse/*.whl

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload wheelhouse/*

#  upload_all:
#    name: Upload if release
#    needs: [build_wheels, build_win27_wheels, build_sdist]
#    runs-on: ubuntu-latest
#    if: github.event_name == 'release' && github.event.action == 'published'
#
#    steps:
#    - uses: actions/setup-python@v2
#
#    - uses: actions/download-artifact@v2
#      with:
#        name: artifact
#        path: dist
#
#    - uses: pypa/gh-action-pypi-publish@v1.4.1
#      with:
#        user: __token__
#        password: ${{ secrets.pypi_password }}
