name: Publish python-client

on: workflow_dispatch  # Manual trigger

jobs:
  build_and_deploy:
    name: Create and publish package to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/metaspace

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and publish
      working-directory: ./metaspace/python-client
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Publish package on PyPI
      user: pypa/gh-action-pypi-publish@v1.8.11
      with:
        user: __token__
        password: ${{ secrets.PYTHON_CLIENT_PYPI_API_TOKEN }}